pantheon-systems/terminus-build-tools-plugin

src/Commands/BuildToolsCommand.php
This runs only if the environment is re-used rather than created.
=> Add a clone-content flag to build-env:create 

src/Commands/BuildToolsCommand.php
=> Provide authentication to the GitHub /repos/project/pull request 

src/Commands/BuildToolsCommand.php
Ask for credentials using 'askHidden'. Prompt for admin password for test site.
=> Improve messaging around the build-env:create-project command. 

src/Commands/BuildToolsCommand.php
Check site name before prompting for anything. Prompt for a team if one is not provided.
=> Improve validation. 

circle.yml, src/Commands/BuildToolsCommand.php
Allow empty string for admin-password.
=> Improve formatting of prompts in create-project. 

src/Commands/BuildToolsBase.php
One more for https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/37
=> Adds missing $this in BuildToolsBase method calls

src/Commands/BuildToolsBase.php
Bring over fixes from the 1.x branch.
=> Changes needed to support drops-7.

src/Commands/BuildToolsBase.php, src/Commands/ProjectCreateCommand.php, src/Task/Ssh/CreateKeys.php
Always empty -- but select the correct one to match the framework needed. Also push to github repository early.
=> Autodetect the upstream to use

src/Commands/BuildToolsCommand.php
A 1.x version of https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/66
=> WordPress install fix

.circleci/config.yml, .circleci/test-example-repo.sh
=> cleanup PR_BRANCH definition

src/Commands/BuildToolsBase.php
before deleting a multidev environment; continue to refrain from deleting multidev environments that have at least one open pull request.
=> Require at least one closed pull request 

src/Commands/BuildToolsCommand.php
=> Only delete multidevs for PRs that have at least one closed PR

src/Commands/BuildToolsBase.php, src/Commands/EnvObliterateCommand.php, src/Commands/ProjectCreateCommand.php, src/ServiceProviders/CIProviders/CIProvider.php, src/ServiceProviders/CIProviders/CircleCIProvider.php, src/ServiceProviders/ProviderInterface.php, src/ServiceProviders/ProviderManager.php, src/ServiceProviders/RepositoryProviders/BitbucketProvider.php, src/ServiceProviders/RepositoryProviders/GitProvider.php, src/ServiceProviders/RepositoryProviders/GithubProvider.php
Allow it to work with multiple git repository providers.
=> Refactor the build:env:obliterate command 

src/Commands/BuildToolsBase.php, src/Commands/ProjectCreateCommand.php
Now includes the source repository used.
=> Provide a better initial commit message

src/Commands/BuildToolsBase.php, src/Commands/EnvDeleteCommand.php, src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php, src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php, src/ServiceProviders/RepositoryProviders/GitProvider.php
Implemented support for multiple Git providers - auto detected from repo - in build:env:delete.
=> Multi-Git-provider support for build:env:delete

.circleci/config.yml, .circleci/test-example-repo.sh, DEVELOPMENT.md
This provides instructions for doing development on a fork.
As well as development readme, also makes a few changes to allow forked branches to be automatically tested (with a bit of setup).
Before merging, it will need a couple changes to your CircleCI's settings. Specifically, create a few environment variables:
- TERMINUS_ORG
- BITBUCKET_USER
- GITHUB_USER
=> Development instructions/Making CI work with forks

src/Commands/EnvCreateCommand.php
Need to do the slower thing (commit after creating mulitdev) if pantheon.upstream.yml is modified.
=> React to changes in pantheon.upstream.yml in pull requests

.circleci/config.yml, .circleci/test-example-repo.sh, README.md, src/Commands/EnvObliterateCommand.php, src/Commands/ProjectCreateCommand.php, src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php, src/Task/CI/Setup.php
The culmination of #150 et. al.
=> Philltran improved bitbucket support

.circleci/config.yml, .circleci/test-example-repo.sh, src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php
Duplicate of #135, but with permissions to run tests.
=> Nick wilde1990 improved bitbucket support

src/Commands/BuildToolsCommand.php
Backporting the fix from #158 into the `1.x` branch.
=> backport of #158 to 1.x branch

.circleci/config.yml, .circleci/test-github-repair.sh, src/Commands/BuildToolsBase.php, src/Commands/CIConfigureCommand.php, src/Commands/EnvDeleteCommand.php, src/Commands/ProjectCreateCommand.php, src/Commands/ProjectRepairCommand.php, src/Credentials/CredentialManager.php, src/Credentials/CredentialRequest.php, src/Credentials/CredentialRequestInterface.php, src/ServiceProviders/CIProviders/CIState.php, src/ServiceProviders/CIProviders/CircleCI/CircleCIProvider.php, src/ServiceProviders/CIProviders/GitLabCI/GitLabCIProvider.php, src/ServiceProviders/ProviderEnvironment.php, src/ServiceProviders/ProviderManager.php, src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php, src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php, src/ServiceProviders/RepositoryProviders/GitLab/GitLabProvider.php, src/ServiceProviders/RepositoryProviders/GitProvider.php, src/ServiceProviders/SiteProviders/PantheonProvider.php, src/ServiceProviders/SiteProviders/SiteEnvironment.php, src/ServiceProviders/SiteProviders/SiteProvider.php, src/Task/CI/Setup.php, src/Task/Repository/RepositoryCreate.php, src/Task/Ssh/CreateKeys.php, src/Task/Ssh/KeyPairReciever.php
Factor out PantheonProvider as a new 'site' provider. 
Add 'build:project:repair' command.
=> BT-5: build:project:repair

.circleci/config.yml, src/API/Bitbucket/BitbucketAPITrait.php, src/API/GitHub/GitHubAPITrait.php, src/API/GitLab/GitLabAPITrait.php, src/Commands/BuildToolsBase.php, src/Commands/EnvMergeCommand.php, src/Commands/EnvObliterateCommand.php, src/Commands/ProjectInfoCommand.php, src/Credentials/CredentialRequest.php, src/ServiceProviders/CIProviders/BitbucketPipelines/BitbucketPipelinesProvider.php, src/ServiceProviders/CIProviders/GitLabCI/GitLabCIProvider.php, src/ServiceProviders/ProviderManager.php, src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php, src/ServiceProviders/SiteProviders/PantheonProvider.php, src/Task/Ssh/CreateKeys.php
Add a 'key pair receiver' (needs both public and private keys) interface.
=> BT-13: Bitbucket pipelines. 

src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php
Declare namespace of PullRequestInfo before using it. Remove unused method createRepositoryInfo
=> BT-36: Fix another problem with merge to master

.circleci/config.yml, .circleci/test-github-repair.sh, .circleci/test-merge-master.sh, src/API/GitHub/GitHubAPI.php, src/API/WebAPI.php, src/ServiceProviders/CIProviders/CircleCI/CircleCIProvider.php, src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php, src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php, src/ServiceProviders/RepositoryProviders/GitLab/GitLabProvider.php
Also improves testing of merge-to-master step, and fixes a bug in `build:env:delete:pr` for GitHub.
=> BT-39: Only build on pull requests

.circleci/set-up-globals.sh, src/Commands/BuildToolsBase.php
Let's the workflow just run and run and run without getting stuck waiting for the user to accept an SSH host key prompt.
=> BT-27: Use GIT_SSH_COMMAND for pushing to Pantheon

src/API/Bitbucket/BitbucketAPITrait.php, src/API/GitHub/GitHubAPITrait.php, src/API/GitLab/GitLabAPITrait.php, src/Commands/CredentialsClearCommand.php, src/Credentials/CredentialManager.php, src/Credentials/CredentialRequest.php, src/Credentials/CredentialRequestInterface.php, src/ServiceProviders/CIProviders/CircleCI/CircleCIProvider.php
If credentials are mis-entered, validate them against the service provider and ask the user to re-enter them if they do not work.
=> BT-24: Provide opportunity to correct mis-entered credentials

README.md, src/Commands/ProjectCreateCommand.php, src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php, src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php, src/ServiceProviders/RepositoryProviders/GitLab/GitLabProvider.php, src/ServiceProviders/RepositoryProviders/GitProvider.php
Hello,
I've added some functionality to allow for a flag that allows for github repositories created automatically by the tool to also be private.
=> Add functionality and a flag to allow github private repositories.

src/API/Bitbucket/BitbucketAPITrait.php
I added the tokenKey method, and linked the properties required.
=> #199 - add tokenKey method for bitbucket trait

src/Commands/EnvCreateCommand.php
=> Revert to build:env:push if build:env:create is run against dev

src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php
Addresses https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/255
=> Bitbucket privacy

src/API/Bitbucket/BitbucketAPI.php, src/API/GitHub/GitHubAPI.php, src/API/GitLab/GitLabAPI.php, src/API/WebAPI.php
=> Make `isPagedResponse()` and `getPagerInfo()` more flexible and typehint

src/API/WebAPI.php
It's not entirely obvious what's going on, so better to communicate the
intent.
Fixes #266
=> Add some documentation around `checkPagedCallback()`

README.md
=> Remove Bitbucket limitation in README

src/ServiceProviders/RepositoryProviders/GitLab/GitLabProvider.php
Resolves https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/297
I had to create a custom command to see confirm this was actually working -- https://gist.github.com/rvtraveller/faecdc48d23b372ebc712ec847de8ceb
=> Retrieve GitLab merge request states individually.

src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php, src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php, src/ServiceProviders/RepositoryProviders/GitLab/GitLabProvider.php
=> Allow source_branch and sha for GitLab branch name in branchesForPullRequests output

src/Commands/EnvCreateCommand.php
Running tests for PR #328 Adds missing message to Pantheon Push
=> Test run for #328

.circleci/config.yml, src/Commands/ProjectCreateCommand.php
Running tests for #324 Add support for readme templates
=> Running tests for 324

.circleci/config.yml, src/Commands/BuildToolsBase.php
=> Increase workflow timeout and add better logging

.circleci/cleanup-fixtures.sh, README.md
A few fixes:
- Removed duplicated `more`
- Repositioned comma
- Fixed `liiked` word
=> Updated README.ME

src/Commands/BuildToolsBase.php, src/Commands/ProjectCreateCommand.php, src/Utility/ExecWithRedactionTrait.php
These fixes allow this plugin to work in t3 without breaking support for t2 :)
=> Backport some fixes introduced in 3.x branch to support t3.

.circleci/set-up-globals.sh, README.md, composer.lock, src/Commands/BuildToolsBase.php, src/Commands/ProjectCreateCommand.php
=> Get right install and composer require commands based on the app
