- README.md
- circle.yml
- example.circle.yml
- src/Commands/BuildToolsCommand.php
Ported from https://github.com/stevector/pantheon-create-project.
See #7
> Add build-env:create-project command 

- example.circle.yml
There is a problem with the existing logic in creating Multidev branch naming that in cases where there are multiple underscores they don't properly get filtered into Multidev acceptable naming. FOr example:
underscore_name_fix
update_local_dev_readme
The updated replacement logic will filter out cases like these.
> Better Handling of Multidev Branch Naming to Handle Multiple Underscores

- src/Commands/BuildToolsCommand.php
We do not want the environment to be automatically deleted on merge.
> Add a --delete option to 'merge' command, and make the default FALSE

- circle.yml
- src/Commands/BuildToolsCommand.php
Ensure we are using a consistent version of the Terminus Build Tools plugin, so that we do not vary the System-Under-Test in the derived project we create.
> Use a consistent System-Under-Test

- circle.yml
- src/Commands/BuildToolsCommand.php
Exporting configuration on site-install allows us to simplify the circle.yml file, and also gives the user a smoother DX when spinning up a new site, as that's one less thing they'll need to do manually.
> Export config on install

- src/Commands/BuildToolsCommand.php
… so that the build metadata will always be correct.
> Always add a remote 'origin' in create-project

- src/Commands/ProjectCreateCommand.php
Updates https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/37 for syntax error, failing build.
> fixes syntax error in ProjectCreateCommand

- src/Commands/BuildToolsCommand.php
This PR is meant to solve: https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/58
@greg-1-anderson If the `temp-local-copy-of-pantheon-master` branch is deleted after the push, what would be the branch to checkout instead?
> Checkout Pantheon's master branch rather than source master

- src/Commands/ProjectCreateCommand.php
PR https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/60 is meant to add testing support for a WordPress repo. It is currently failing because of problems switching the Drupal test to Circle 2. I'd like to get that problem resolved today. But I also want to unblock the WordPress functionality change itself. And that is very small, this one line.
@greg-1-anderson do you think we can merge this change independent of https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/60
> WordPress install fix

- README.md
- src/Commands/BuildToolsBase.php
A shockingly short PR that provides substantial benefit.
> Fixes #68: Allow users to supply their own shortcuts for build:project:create

- src/Commands/CommentAddCommitCommand.php
- src/Commands/EnvCreateCommand.php
We must pass sha to the commit comment command rather than take current local working copy sha.
> Fix sha hash used in commit comments.

- src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php
pushRepository() will fail for BitBucket if there is an '@' in either username or password. URL Encoded both sides of the token to escape any unwanted characters in the request.
> BitBucket Username and Password need to be URL encoded in token.

- src/ServiceProviders/CIProviders/CircleCI/CircleCIProvider.php
This will fix the invalid link/image to CircleCI that is in the generated readme when using a bitbucket repo
> Add CircleCI project page mapping for BitBucket repositories

- src/Commands/BuildToolsBase.php
In my environment with zero open and zero closed pull requests, build:env:delete (and build:env:delete:ci) refuses to delete any environments.
This patch fixes the logic problem.
Works in my limited testing, but haven't tested against environments with open PRs or multidev-branches that need to be preserved.
> Fixes logic issues in branch-preservation

- src/Task/Ssh/CreateKeys.php
Add -m PEM to ssh-keygen to output key in PEM format so CircleCI API will accept ssh-key
Fixes[ Issue #158 ](https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/158)
> Set ssh key gen to use PEM format to address Issue #158 . with CircleCI

- src/Commands/BuildToolsBase.php
Allow the `.` character in the project name.
Fixes #163.
> fix: correct regular expression to parse project

- README.md
I was trying to run first the build command when I was trying to follow the instructions because that was the first code that I saw and ran into an error. I have to read the whole instruction first to find out that I need to do the installation instruction at the bottom of the document, might help first time users to know the Terminus plugin installation before running any code outlined in this doc.
> Updated readme with a link to the installation

- src/API/Bitbucket/BitbucketAPI.php
- src/API/Bitbucket/BitbucketAPITrait.php
- src/API/GitHub/GitHubAPI.php
- src/API/GitHub/GitHubAPITrait.php
- src/API/PullRequestInfo.php
- src/API/WebAPI.php
- src/API/WebAPIInterface.php
- src/Commands/BuildToolsBase.php
- src/ServiceProviders/ProviderEnvironment.php
- src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php
- src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php
- src/ServiceProviders/RepositoryProviders/GitLab/GitLabProvider.php
- src/ServiceProviders/RepositoryProviders/RepositoryEnvironment.php
- src/ServiceProviders/ServiceTokenStorage.php
- src/Utility/MultiDevRetention.php
I factored `GitHubAPI` out of the GitHub provider so that I could refactor `WebAPI` out of that, and use it to build `BitbucketAPI`. This allows both the Bitbucket Repository provider and the Bitbucket CI Pipelines provider to use the same API object to talk to the BitBucket API.  This will also afford us the ability to re-use some of the paged API request code in BitBucket + GitLab, e.g. when searching for pull requests.
The GitLabProvider still needs to be refactored to follow suit.
> Split out GitHub API as a separate object called by the GitHub service provider

- src/ServiceProviders/CIProviders/CircleCI/CircleCIProvider.php
Recently, we started seeing CircleCI responding with a 500 error to all API requests. This was only happening for requests made directly via Build Tools -- using a proxy such as Charles and then copying the captured request to command line curl worked fine. Turns out, CLI curl adds an `Accept` header to the request (which is not present via Build Tools). The [docs](https://circleci.com/docs/api/#accept-header) seem to indicate that an `Accept` header is not required...but reality seems to prove otherwise. Let's add an `Accept: application/json` header for CircleCI as we don't need extra whitespace or comments in the response anyway.
> Update Circle API calls to prevent 500 error

- src/API/GitLab/GitLabAPI.php
Due to a bug in the way Terminus pulls environment configuration values with Robo, we (unfortunately) need to add manual detection.
> Add temporary environment variable detection to GitLab URL detection

- src/Commands/BuildToolsBase.php
- src/Commands/EnvCreateCommand.php
- src/Commands/EnvPushCommand.php
Resolves #161 
By default, Build Tools will create an additional commit when pushing to Pantheon with a commit message of "Build assets for <environment>". Prior commit history from the external repository provider is retained as the "Build assets" command is just an additional commit.
Using `build:env:create` or `build:env:push` you can now include an optional `--message` flag to override the commit message on the build commit.
Should the `--message` option not be used, the existing functionality will be used including the "copying" of commit messages from the external provider to Pantheon and the "Build assets for <environment>"
> Support for custom build asset messages.

- src/Commands/BuildToolsBase.php
This commit fixes an error with `build:env:create` which currently depends on the source environment being the `dev` environment (since it is the only one that has a `git_url`).
This is fixed by always using the `dev` environment for `BuildToolsBase ::addPantheonRemote()` since that is the only logical entry point to the codebase of a site. A new branch will still be created for the multidev environment as expected.
> allow build:env:create to clone test, live, etc

- src/API/GitLab/GitLabAPITrait.php
- src/ServiceProviders/CIProviders/GitLabCI/GitLabCIProvider.php
Part of the resolution for https://github.com/pantheon-systems/example-wordpress-composer/issues/134.
GitLab requires scheduled pipeline jobs to be completed via the API or via the UI. This adds support for setup via the "start testing" step of Build Tools. Scheduled Pipelines in GitLab run on a branch and act as if someone had triggered a CI run for that branch.
Note: This is, in many ways, dependent on https://github.com/pantheon-systems/example-wordpress-composer/pull/158 which should be merged and replicated on Drops 7 & 8 before fully merging this.
> Add support for creating scheduled GitLab Pipeline

- README.md
- src/Commands/BuildToolsBase.php
- src/Commands/ProjectCreateCommand.php
With the new region options available in Pantheon.  I needed to start creating my sites in the CA region and so I needed this plugin to allow passing the option --region to the terminus site:create command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pantheon-systems/terminus-build-tools-plugin/225)
> Allow setting the region when creating a site

- src/API/Bitbucket/BitbucketAPI.php
- src/API/WebAPI.php
- src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php
BitBucket's API response is shaped differently than GitHub and GitLab.
The values themselves are nested in a `values` key.
Fixes #261
> Fix PHP notices when interacting with BitBucket API data 

- src/API/Bitbucket/BitbucketAPI.php
BitBucket includes the `next` parameter in its response, not as a
header.
Depends on #263, #264 
Fixes #253
> Update `BitbucketAPI` to handle API data pagination

- src/Commands/ProjectCreateCommand.php
- src/Commands/ProjectRepairCommand.php
- src/ServiceProviders/RepositoryProviders/BaseGitProvider.php
- src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php
- src/ServiceProviders/RepositoryProviders/GitProvider.php
Allowing git providers to specify their own build secrets addresses issues like https://github.com/pantheon-systems/quicksilver-pushback/issues/12 where different providers expect different credentials.
Adds `GitProvider::getSecretValues` interface method, and default implementation to match existing behavior.
> Allow git providers to provide build secrets.

- README.md
- src/Commands/CommentAddCommitCommand.php
- src/Commands/CommentAddPullRequestCommand.php
> Better docs for build:comment:add:commit and build:comment:add:pr

- src/Commands/ProjectCreateCommand.php
Adds documentation for all options in `build:project:create` command.
> Add documentation for build:project:create options

- README.md
Closes #274. Add configuration example for self-hosted GitLab hostname.
> Add configuration example for self-hosted GitLab hostname.

- README.md
- src/Commands/ProjectCreateCommand.php
- src/Commands/ProjectRepairCommand.php
- src/ServiceProviders/SiteProviders/PantheonProvider.php
- src/ServiceProviders/SiteProviders/SiteEnvironment.php
We tend to avoid using "admin" as a username so I've added support for providing a custom admin username via the build:project:create option with the key "admin-username".
I also cleaned up the getters and setters as the parameters were named incorrectly.
> Added support for changing the admin username

- src/Commands/EnvCreateCommand.php
`\Pantheon\TerminusBuildTools\Commands\EnvCreateCommand::createBuildEnv` aka  `build:env:create` accepts a `message` option, but ignores the input.
This patch passes `message` through to `\Pantheon\TerminusBuildTools\Commands\BuildToolsBase::pushCodeToPantheon`
> Adds missing message to pantheon push

- README.md
I noticed the install snippet was still referencing the last pre-release (beta-17) instead of the 2.0.0 stable release.
> Update composer install step to stable release

- src/ServiceProviders/CIProviders/BitbucketPipelines/BitbucketPipelinesProvider.php
Missing closing bracket generates incorrect Bitbucket flavoured markdown.
> Fixes typo in Bitbucket Pipelines badge

- src/Commands/BuildToolsBase.php
Pantheon workflows can take longer than 60 seconds to complete, so let's bump up the timeout.
Also, we should add better logging around this.
Success after this change:
```
[notice] Workflow 'Sync code on "dev"' running.
[notice] Workflow 'Sync code on "dev"' succeeded.
[notice] Workflow succeeded
```
Timeout after this change:
```
[notice] Workflow 'Sync code on "dev"' running.
[warning] Waited '2' seconds, giving up waiting for workflow to finish
```
> BUGS-3249: Increase workflow timeout and add better logging

- .circleci/config.yml
- README.md
- src/Commands/BuildToolsBase.php
- src/Commands/EnvCreateCommand.php
- src/Commands/EnvMergeCommand.php
- src/Commands/EnvPushCommand.php
This PR is a replacement for https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/202 which has been used by our CircleCI Orb for the last year and is far behind master. The motivation here is to be able to use the Build Tools with little, or no risk of a force push overwriting history.
To test this change, I [also made a PR on the orb to use this version of Build Tools](https://github.com/pantheon-systems/circleci-orb/pull/45).
I then used that version of the orb in [a build](https://app.circleci.com/pipelines/github/stevector/nerdologues-d8/347/workflows/ceb0a006-0568-40c7-a612-6afbe0f7719c/jobs/4271) on a [consumer of the Orb](https://github.com/stevector/nerdologues-d8/pull/366/commits/8516b20965dfa445cdabcefa331cf4aa7efc523c).
Here's a screenshot of the section of the …
> Adding an option for --no-git-force on build:env:create and build:env:push

- src/API/GitHub/GitHubAPITrait.php
- src/API/GitLab/GitLabAPITrait.php
- src/Commands/SelfInfoCommand.php
- src/ServiceProviders/CIProviders/BaseCIProvider.php
- src/ServiceProviders/ProviderEnvironment.php
- src/ServiceProviders/ProviderManager.php
- src/ServiceProviders/SiteProviders/PantheonProvider.php
Resolves #288.
The command currently shows the directory where you have Build Tools installed, the providers that have tokens set up already, and where to find new releases.
```
terminus build:self:info
```
> Add self info command for build tools.

- src/API/GitHub/GitHubAPITrait.php
Addresses the issue documented here:
https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/374
> ISSUE-374: Updated the GitHub regex to support their new personal access token format

- src/API/PullRequestInfo.php
Fixes the `branchName` method in PullRequestInfo class to avoid infinite recursion.
> Fix branch name method to avoid infinite recursion

- README.md
- src/Commands/BuildToolsBase.php
- src/Commands/ProjectCreateCommand.php
- src/ServiceProviders/CIProviders/CircleCI/CircleCIProvider.php
To use a private repository, define the auth string like this:
```
export TERMINUS_BUILD_TOOLS_COMPOSER_AUTH=json_encoded_string
```
or in .terminus/config.yml as described at https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/main/src/Utility/Config.php#L21
Then, in the build:project:create command, pass a composer-repository option like this:
```
terminus build:project:create --template-repository="https://repo.packagist.com/kporras07" kporras07/example-drops-8-test my-project
```
To use a git repository, use the terminus command like this:
```
terminus build:project:create --template-repository="git@github.com:kporras07/myrepo.git" kporras07/myrepo-template my-project
```
The package name in the composer.json file into the template repo should be …
> [CMS-145] [CMS-146] Add template repository option to project create command.

- README.md
- composer.json
- composer.lock
- src/Commands/BuildToolsBase.php
- src/Commands/ProjectCreateCommand.php
- src/ServiceProviders/CIProviders/CircleCI/CircleCIProvider.php
This PR allows you to create sites using templates that don't have CI in them (e.g. pantheon-upstreams/drupal-project). By default, it uses pantheon-systems/tbt-ci-integrations but it could be overriden using --ci-template option.
Example command:
```
terminus build:project:create git@github.com:pantheon-upstreams/drupal-project.git <project_name> --stability=dev
```
> Add ci from other repo

- README.md
- src/Commands/BuildToolsBase.php
This PR allows using "d9" as source on project create.
I'll also create a docs PR for this.
> CMS-254: Make Drupal 9 discoverable on build tools.

- .circleci/set-up-globals.sh
- composer.lock
- src/Commands/BuildToolsBase.php
- src/Commands/ProjectCreateCommand.php
This will enable terminus build tools to work properly with unofficial Wordpress upstreams with CI not included in the same repo. An example of this is https://github.com/pantheon-upstreams/wordpress-project
```
terminus build:project:create git@github.com:pantheon-upstreams/wordpress-project.git --stability=dev  mywpsite
```
> Get right install and composer require commands based on the app.

- README.md
- src/Commands/GitignoreCutCommand.php
- src/Commands/ProjectCreateCommand.php
This PR adds a new command to cut on the cut mark for a gitignore file. This was handled by a composer script in d8, wp and d7 templates but we're adding it to build tools in order to be able to use it for non-standard templates.
Also, the cut mark is added to .gitignore during site creation if the source repo doesn't have it.
> CMS-294: Add .gitignore cut command and append cut line when not present in source .gitignore.
